{% set name = "BSMAPz" %}
{% set version = "development" %}

about:
  home: https://github.com/zyndagj/BSMAPz
  license: GNU GPL v3
  license_family: GPL
  license_file: LICENSE.txt
  summary: An optimized fork of BSMAP created by Greg Zynda

build:
  number: 0

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

requirements:
  build:
    - python=2.7
    - {{ compiler('cxx') }}
    - zlib
    - samtools
    - pysam
    - conda-verify
  host:
    - zlib
    - python=2.7
  run:
    - python=2.7
    - samtools
    - pysam

test:
  commands:
    - bsmapz -h 2>&1 | grep "bsmap" > /dev/null
    - methratio.py -h 2>&1 | grep "ratios" > /dev/null
    - methdiff.py -h 2>&1 | grep "Usage" > /dev/null

extra:
  identifiers:
    - biotools:bsmap
  doi: doi.org/10.1186/1471-2105-10-232
